# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# latest release as of 2017-09-22
# uses GHC 8.0.2
resolver: lts-9.5

build:
  library-profiling: true
  executable-profiling: true
