# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# latest release for GHC 8.6.5 as of 2020-02-17
# uses GHC 8.6.5
resolver: lts-14.27

extra-deps:
  - flock-0.3.1.8
  - rdtsc-1.3.0.1@sha256:0a6e8dc715ba82ad72c7e2b1c2f468999559bec059d50540719a80b00dcc4e66
